export const QUESTIONNAIRES_REPOSITORY = "QUESTIONNAIRES_REPOSITORY"
export const QUESTIONNAIRES_FILLINGS_REPOSITORY = "QUESTIONNAIRES_FILLINGS_REPOSITORY"
export const QUESTIONS_REPOSITORY = "QUESTIONS_REPOSITORY"
export const QUESTIONS_ANSWERS_REPOSITORY = "QUESTIONS_ANSWERS_REPOSITORY"
